[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
region = "ap-south-1"

[[edge_functions]]
path = "/*"
function = "proxy"
